# Generated by Django 6.0.7 on 2026-08-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_gender_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-age'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='customer_user_profile',
        ),
    ]
