# Generated by Django 6.0.7 on 2026-08-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options_alter_userprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['department'], name='users_emplo_departm_4a62d3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 18)), name='employee_age_must_be_18_or_above')],
                'unique_together': {('department', 'employee_id')},
            },
        ),
    ]
